//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrazyCola
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int usuario_id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correo_electronico { get; set; }
        public string contrasena { get; set; }
        public Nullable<bool> is_administrador { get; set; }
        public Nullable<int> almacen_id { get; set; }
    
        public virtual almacen almacen { get; set; }
    }
}
